// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSubscription = `-- name: CancelSubscription :exec
UPDATE subscriptions
SET
status='cancelled',
updated_at=NOW()
WHERE id=$1
`

func (q *Queries) CancelSubscription(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, cancelSubscription, id)
	return err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    user_id,
    name,
    category,
    amount,
    currency,
    billing_cycle,
    start_date,
    next_billing_date,
    auto_renew,
    website,
    notes
)
VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11
)
RETURNING id, user_id, name, category, amount, currency, billing_cycle, start_date, next_billing_date, auto_renew, website, notes, status, created_at, updated_at
`

type CreateSubscriptionParams struct {
	UserID          int64
	Name            string
	Category        string
	Amount          pgtype.Numeric
	Currency        string
	BillingCycle    BillingCycle
	StartDate       pgtype.Date
	NextBillingDate pgtype.Date
	AutoRenew       bool
	Website         pgtype.Text
	Notes           pgtype.Text
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.Name,
		arg.Category,
		arg.Amount,
		arg.Currency,
		arg.BillingCycle,
		arg.StartDate,
		arg.NextBillingDate,
		arg.AutoRenew,
		arg.Website,
		arg.Notes,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Category,
		&i.Amount,
		&i.Currency,
		&i.BillingCycle,
		&i.StartDate,
		&i.NextBillingDate,
		&i.AutoRenew,
		&i.Website,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, user_id, name, category, amount, currency, billing_cycle, start_date, next_billing_date, auto_renew, website, notes, status, created_at, updated_at
FROM subscriptions
WHERE id=$1
`

func (q *Queries) GetSubscription(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Category,
		&i.Amount,
		&i.Currency,
		&i.BillingCycle,
		&i.StartDate,
		&i.NextBillingDate,
		&i.AutoRenew,
		&i.Website,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, user_id, name, category, amount, currency, billing_cycle, start_date, next_billing_date, auto_renew, website, notes, status, created_at, updated_at
FROM subscriptions
WHERE user_id=$1
AND status='active'
ORDER BY next_billing_date
`

func (q *Queries) ListSubscriptions(ctx context.Context, userID int64) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Category,
			&i.Amount,
			&i.Currency,
			&i.BillingCycle,
			&i.StartDate,
			&i.NextBillingDate,
			&i.AutoRenew,
			&i.Website,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET
name=$2,
category=$3,
amount=$4,
currency=$5,
billing_cycle=$6,
start_date=$7,
next_billing_date=$8,
auto_renew=$9,
website=$10,
notes=$11,
updated_at=NOW()
WHERE id=$1
RETURNING id, user_id, name, category, amount, currency, billing_cycle, start_date, next_billing_date, auto_renew, website, notes, status, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	ID              int64
	Name            string
	Category        string
	Amount          pgtype.Numeric
	Currency        string
	BillingCycle    BillingCycle
	StartDate       pgtype.Date
	NextBillingDate pgtype.Date
	AutoRenew       bool
	Website         pgtype.Text
	Notes           pgtype.Text
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Amount,
		arg.Currency,
		arg.BillingCycle,
		arg.StartDate,
		arg.NextBillingDate,
		arg.AutoRenew,
		arg.Website,
		arg.Notes,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Category,
		&i.Amount,
		&i.Currency,
		&i.BillingCycle,
		&i.StartDate,
		&i.NextBillingDate,
		&i.AutoRenew,
		&i.Website,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
